name: Build Docker Image

on:
  push:
    branches:
      - 'master'
      - 'main'
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest

      strategy:
        matrix:
          python_version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python_version: ${{matrix.python_version}}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r api/requirements-dev.txt

        - name: Test API
          run: |
            make -C api test

  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Tag Docker images for GHCR
        run: |
          docker tag wikipost_api ghcr.io/marcorfilacarreras/wikipost-api:latest
          docker tag wikipost_web ghcr.io/marcorfilacarreras/wikipost-web:latest

      - name: Push Docker images to GHCR
        run: |
          docker push ghcr.io/marcorfilacarreras/wikipost-api:latest
          docker push ghcr.io/marcorfilacarreras/wikipost-web:latest
